datasources:
  foo:
    url: jdbc:tc:mysql:5.6.23:///test
    driverClassName: org.testcontainers.jdbc.ContainerDatabaseDriver
    schema-generate: CREATE
    dialect: mysql
micronaut:
  distributed-lock:
    datasource-name: foo
    dialect: mysql
