datasources:
  foo:
    url: jdbc:tc:postgresql:12:///distlock
    driverClassName: org.testcontainers.jdbc.ContainerDatabaseDriver
    schema-generate: CREATE_DROP
    dialect: postgres
micronaut:
  distributed-lock:
    database-name: foo
